### ISSUE TITLE
TRAP #15 Function #6 should print, not send (despite the name)

### ISSUE THREAD

**Issue by roscopeco** [rosco-m68k/rosco_m68k#240]
The Easy68k TRAP #15 function #6 , despite being named `SENDCHAR`, is documented to _display_ the character, so it should probably use the underlying `PRINTCHAR` EFP rather than the `SENDCHAR` one.

It might be worth (somehow) checking we're aligned with Easy68k on this...

(See: https://github.com/rosco-m68k/rosco_m68k/blob/develop/code/firmware/rosco_m68k_v1.3/InterfaceReference.md#1327-sendchar-function-6 )

**Comment by 0xTJ** [comment]
Based on the EASy68K reference, it looks like `TRAP #15` function `#6` should go to the same place as `#0`, `#1`, `#3`, and all the others that "display", so I'd agree that it should go through the `PRINTCHAR` route. I think everything for `TRAP #15` should go through the default console instead of default UART (and as far as I can see this is the only one that doesn't do this yet).

Might also be worth considering (for any added user input devices, I've been looking at making a PS/2 board) adding FW/EFP routines for generic user input, as opposed to UART input; something that is to `RECVCHAR` what `PRINTCHAR` is to `SENDCHAR`.
